# Generated by Django 3.2.5 on 2022-01-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainStreet', models.CharField(max_length=2048)),
                ('additionalStreet', models.CharField(max_length=2048)),
                ('streetNumber', models.IntegerField()),
                ('zip', models.IntegerField()),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logos/')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1028)),
                ('phone', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=128)),
                ('website', models.CharField(max_length=512, null=True)),
                ('active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.placeaddress')),
            ],
        ),
    ]
