# Generated by Django 3.2.5 on 2022-01-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=1028, null=True),
        ),
    ]
