# Generated by Django 3.2.5 on 2022-01-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeaddress',
            old_name='additionalStreet',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='placeaddress',
            old_name='mainStreet',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='placeaddress',
            name='streetNumber',
        ),
        migrations.AddField(
            model_name='placeaddress',
            name='zone',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
