# Generated by Django 3.2.5 on 2022-01-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_placeaddress_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='placeaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
