# Generated by Django 3.2.5 on 2022-01-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_auto_20220104_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='amount_tests',
            field=models.IntegerField(null=True),
        ),
    ]
