# Generated by Django 3.2.5 on 2022-01-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_place_amount_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='amount_tests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
