# Generated by Django 3.2.5 on 2022-01-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_alter_place_amount_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
